language: python
sudo: false

env:
  global:
  - PIP_DEPS="pytest coveralls pytest-cov flake8"

python:
- '3.7.6'

#script:
#- cd $HOME/diff_classifier
#- python tests.py

install:
- pip install -U tox-travis coverage coveralls
- travis_retry pip install $PIP_DEPS
- travis_retry pip install -r requirements.txt
- travis_retry pip install -e .

script:
- flake8 --ignore N802,N806 `find . -name \*.py | grep -v setup.py | grep -v version.py | grep -v __init__.py | grep -v /doc/`
- py.test --pyargs diff_predictor --cov-report term-missing --cov=diff_predictor
- coverage report

after_success:
- ls -a
- coveralls
